import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'support-triage';
const k = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.care, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const CARE: RosterEntry[] = [
  k('support-triage', 'Support Triage', 'Sorts every inbound message', 'lead', ['support-inbox', 'gmail', 'claude-code'],
    'Sorts contact form, email and marketplace messages into skip, info, action and urgent.',
    'Triage inbound', 'Skip, info, action, urgent.',
    ['Pull new messages from the contact form, the inbox and Amazon',
     'Classify each: skip, info only, action needed, urgent',
     'Route action items to Reply Drafter, Refund Handler or Shipping Tracker',
     'Route urgent and press to Escalation Manager',
     'Record first response time per message',
     'Report the day\'s volume and top issues to Care Reporter'],
    true, ['Triaged 84 messages: 31 info, 44 action, 6 urgent, 3 skipped', 'Median first response 41 minutes, under the one hour target', 'Top issue today: where is my order (Canada customs)', 'Press enquiry routed to Escalation Manager within 5 minutes']),
  k('reply-drafter', 'Reply Drafter', 'Drafts, never sends', 'worker', ['support-inbox', 'claude-code'],
    'Drafts every reply in brand voice inside the allowlist. Drafts only, a human sends.',
    'Draft the replies', 'Brand voice, allowlist, human sends.',
    ['Take the action items from Support Triage',
     'Draft the reply from the FAQ Keeper answers where one exists',
     'Keep every claim inside the allowlist',
     'Queue the draft for a human to send',
     'Log which FAQ answered it so FAQ Keeper sees the gaps']),
  k('dm-responder', 'DM Responder', 'TikTok and Instagram DMs', 'worker', ['zernio', 'claude-code'],
    'Answers questions in TikTok and Instagram DMs and comments, and hands buying intent to the store.',
    'Answer the DMs', 'Questions answered, intent handed over.',
    ['Pull new DMs and comment questions',
     'Answer from the FAQ Keeper answers',
     'Send buying intent the product link and log it for the funnel',
     'Escalate anything about medical conditions to FAQ Keeper',
     'Report volume to Care Reporter']),
  k('refund-handler', 'Refund Handler', 'The 60-day guarantee', 'specialist', ['shopify', 'klaviyo'],
    'Handles guarantee requests: checks nights used, offers the 21 Nights path first, processes when due.',
    'Handle refund requests', 'Nights used, coaching first, refund when due.',
    ['Take the refund request and the order date',
     'Check how many nights the customer has used the device',
     'Under 21 nights: offer the 21 Nights Coach path and a check-in date',
     'Over 21 nights or declined: process the refund inside the guarantee terms',
     'Record the stated reason for Voice of Customer',
     'Report refund count and saved count to Care Reporter'],
    true, ['12 requests this week: 5 coached and kept, 7 refunded, all inside the window', 'Reason logged most: "no change after two weeks"; 4 of those under 14 nights', 'Kidzzz refund: child would not keep it on; reason filed for Offer Designer', 'Refund rate this month 4.2%']),
  k('shipping-tracker', 'Shipping Tracker', 'Where is my order', 'worker', ['shopify'],
    'Answers where is my order, customs and duties across 40 countries.',
    'Track shipping questions', 'Orders, customs, duties.',
    ['Take the order number from the message',
     'Pull tracking from Shopify and the carrier',
     'Answer with the next scan and the expected date',
     'Explain duties for the destination when asked',
     'Flag any parcel stuck over five days to Support Triage']),
  k('faq-keeper', 'FAQ Keeper', 'Approved sensitive answers', 'worker', ['gbrain', 'claude-code'],
    'Keeps the approved answers for infants, eyes, pregnancy and medication. Anything outside it escalates.',
    'Keep the approved answers', 'Sensitive questions, approved wording.',
    ['Maintain the approved answer for each sensitive question',
     'Source each answer from the evidence base',
     'Refuse to answer outside the list and escalate to a human',
     'Add new questions from Reply Drafter\'s gap log',
     'Review with Compliance Auditor monthly']),
  k('escalation-manager', 'Escalation Manager', 'What reaches Yannick', 'worker', ['gmail', 'slack'],
    'Sends press, retail buyers, clinicians and angry customers to Yannick with context.',
    'Manage escalations', 'Press, buyers, clinicians, anger.',
    ['Take urgent items from Support Triage',
     'Attach the customer history and the last three messages',
     'Write the one-line ask for Yannick',
     'Post to Slack and email with the deadline',
     'Track until closed']),
  k('review-monitor', 'Review Monitor', 'Site, Amazon, Ulta reviews', 'worker', ['reviews', 'amazon'],
    'Watches site, Amazon and Ulta reviews, flags one and two stars, drafts replies.',
    'Monitor the reviews', 'Flag low stars, draft replies.',
    ['Pull new reviews from the site, Amazon and Ulta',
     'Flag one and two stars to Support Triage the same day',
     'Draft a reply per review for a human to post',
     'Send verbatims to Voice of Customer',
     'Report rating trend to Care Reporter']),
  k('voice-of-customer', 'Voice of Customer', 'Weekly synthesis', 'specialist', ['claude-code', 'gbrain'],
    'Synthesises objections and questions weekly and feeds Content\'s Comment Reader and Store\'s Page Writer.',
    'Synthesise the customer voice', 'Objections and questions, weekly.',
    ['Collect the week\'s messages, reviews, DMs and refund reasons',
     'Group into objections, questions and praise with counts',
     'Write the top five of each with a verbatim',
     'Send objections to Comment Reader and questions to Page Writer and FAQ Keeper',
     'File the synthesis in the brain',
     'Report shifts week over week to Care Reporter'],
    true, ['Week 36: top objection "does it really work" (41), top question "safe for a 2-year-old" (27)', 'New this week: "can I use it with my Oura ring", sent to Comment Reader as a format idea', 'Praise theme: travel size; sent to Content Planner', 'Synthesis filed; Page Writer picked up the infant safety question']),
  k('team-feed', 'Team Feed', 'Inbox and Slack digest', 'worker', ['gmail', 'slack'],
    'Digests Slack and the inbox so nothing waits on the phone line.',
    'Digest the team feed', 'Inbox and Slack, twice a day.',
    ['Pull unread from the inbox and new Slack messages',
     'Group by thread and flag anything with a customer waiting',
     'Post the digest at 09:00 and 15:00 Hong Kong time',
     'Flag threads with no owner',
     'Report unread counts to Care Reporter']),
  k('care-reporter', 'Care Reporter', 'Response, resolution, refunds', 'worker', ['claude-code'],
    'Reports first response time, resolution time, refund rate and the top five issues.',
    'Report care weekly', 'Response, resolution, refunds, issues.',
    ['Pull first response and resolution times',
     'Pull refund count and rate from Refund Handler',
     'Take the top five issues from Voice of Customer',
     'Write five lines for Yannick',
     'File the table and send Monday']),
];
