import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'content-planner';
const c = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.content, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const CONTENT: RosterEntry[] = [
  c('content-planner', 'Content Planner', 'Weekly calendar with hypotheses', 'lead', ['claude-code', 'zernio'],
    'Plans the weekly calendar: 60 to 90 slots a month, one hypothesis per slot.',
    'Plan the content week', '60 to 90 slots a month, one hypothesis each.',
    ['Read last week\'s kills and winners from Performance Reader',
     'Fill the week: 15 to 22 brand slots across TikTok, Instagram and YouTube Shorts',
     'Assign each slot a lane, an angle and a format, and write its hypothesis',
     'Reserve slots for the 21 Nights series and creator drops',
     'Send the week to Yannick for approval with the previous week\'s numbers on top',
     'Brief Hook Miner and Script Writer once approved'],
    true, ['Week 37: 19 brand slots, 6 creator drops, 21 Nights day-7 episode', 'Calendar approved by Yannick with one swap: debunk format moved to Thursday', 'Week 36: 21 slots posted, 2 winners, feed never dark']),
  c('creator-watcher', 'Creator Watcher', 'Watchlist and outlier scoring', 'specialist', ['apify', 'claude-code'],
    'Keeps a watchlist of 20 to 50 sleep and wellness creators, pulls new posts, scores outliers against each creator\'s baseline.',
    'Watch the creators', 'Watchlist, new posts, outliers.',
    ['Pull new posts from the 40-creator watchlist for the last 30 days',
     'Filter to engagement rate above 0.5 percent to strip brand deals',
     'Score each post against the creator\'s own baseline and rank outliers',
     'Send the top 25 to Video Analyst',
     'Add or drop creators so the list stays at 40',
     'Log the cost of the pull so Finance sees the scraping bill'],
    true, ['Pulled 1,812 posts from 40 creators; 27 outliers above 3x baseline', 'Added 4 creators in the shift-worker lane, dropped 3 dormant', 'Top outlier this week: wearable before-and-after format, 11x baseline', 'Monthly scrape cost $9.06, inside the $15 budget']),
  c('video-analyst', 'Video Analyst', 'Seven-attribute teardown', 'worker', ['claude-code'],
    'Tears down each winning video into topic, angle, hook format, story style, visual format, visuals and audio.',
    'Tear down the winners', 'Seven attributes per video.',
    ['Take the top 25 outliers from Creator Watcher',
     'Record the seven attributes per video: topic, angle, hook, story, visual format, visuals, audio',
     'Note which attributes repeat across winners this week',
     'Send hooks to Hook Miner and formats to Content Planner',
     'Flag any video whose claims would fail the allowlist so nobody copies it']),
  c('comment-reader', 'Comment Reader', 'Objections from comments', 'worker', ['apify', 'claude-code'],
    'Harvests objections and questions from comments and reviews and feeds them to the planners.',
    'Read the comments', 'Objections and questions, weekly.',
    ['Pull comments on Helight posts and on the top competitor posts',
     'Group them into objections, questions and praise',
     'Rank objections by frequency',
     'Merge with Voice of Customer\'s weekly synthesis from Customer Care',
     'Send the top five objections to Content Planner and Hook Miner']),
  c('hook-miner', 'Hook Miner', 'The hook vault', 'specialist', ['claude-code', 'gbrain'],
    'Keeps the vault: winning hooks turned into templates with variable slots.',
    'Maintain the hook vault', 'Winning hooks into slotted templates.',
    ['Take the hooks from Video Analyst and the objections from Comment Reader',
     'Turn each winning hook into a template with variable slots',
     'Tag each template by lane, angle and format',
     'Retire templates that lost three tests in a row',
     'Publish the vault update to the brain for Ad Copywriter and Script Writer',
     'Report vault size and hit rate to Content Planner'],
    true, ['Vault at 214 templates; 9 added, 6 retired', 'Best template this month: "I stopped taking [x] and started doing this", 4 wins', 'Parent lane templates up to 38 after the Kidzzz push', 'Vault published to the brain; Ad Copywriter pulled 12 templates for week 37']),
  c('script-writer', 'Script Writer', 'Decomposed scripts', 'worker', ['claude-code'],
    'Writes scripts by decomposition: research, then hook, then style, then body. Never one-shot.',
    'Write the scripts', 'Research, hook, style, body.',
    ['Take the slot, its hypothesis and the hook template',
     'Write the research note: what the audience already believes',
     'Write the hook from the template, then the body in the chosen style lens',
     'Mark every claim with its allowlist id',
     'Deliver the script to Video Producer and Compliance Auditor together']),
  c('video-producer', 'Video Producer', 'AI video for volume', 'worker', ['arcads', 'remotion', 'higgsfield'],
    'Produces AI-generated video for volume testing and product spotlights from the brand pack.',
    'Produce the videos', 'Volume testing and spotlights.',
    ['Take the approved scripts',
     'Generate scenes, b-roll and product footage from the brand pack templates',
     'Render captions and sound with the Remotion pipeline',
     'Set the AI-generated content disclosure on every synthetic asset',
     'Hand cuts to Edit Assistant with the script attached']),
  c('edit-assistant', 'Edit Assistant', 'Prepares cuts for a human editor', 'worker', ['remotion', 'whisper'],
    'Prepares cuts, captions and crops for a human editor. Editing stays human, and the board says so.',
    'Prepare the edit', 'Cuts and captions for a human editor.',
    ['Transcribe the source with Whisper',
     'Mark the hook and the strongest segments on the transcript',
     'Render a first cut with captions on beat and platform crops',
     'Hand the cut to the human editor with the brief and the transcript',
     'Collect the final and pass it to Publisher']),
  c('publisher', 'Publisher', 'Daily cadence', 'specialist', ['zernio'],
    'Publishes on cadence to TikTok, Instagram and YouTube Shorts. The feed never goes dark.',
    'Publish on cadence', 'Daily, three platforms, never dark.',
    ['Take the next approved post from the calendar',
     'Adapt the caption per platform and confirm the disclosure flag',
     'Publish through Zernio and record the post ids',
     'Verify each went live; retry a failed platform once',
     'Flag any day with no post to Content Planner before noon',
     'Report posted count to Performance Reader'],
    true, ['Posted 3 of 3 today: TikTok, Instagram, Shorts', '21 posts this week, 0 dark days', 'Instagram publish failed once, retried, live at 10:14', 'Creator drop cross-posted with the disclosure flag set']),
  c('creator-recruiter', 'Creator Recruiter', 'Find and vet creators per lane', 'worker', ['claude-code', 'apify'],
    'Finds and vets creators per audience lane: parents, shift workers, wearable optimisers, travellers.',
    'Recruit creators', 'Per lane, vetted.',
    ['Search each lane for creators with engaged audiences under 100k',
     'Check past brand work and any health-claim history',
     'Shortlist five per lane with rates and reach',
     'Send the shortlist to Content Planner for the pick',
     'Open the conversation with the chosen creators']),
  c('creator-briefer', 'Creator Briefer', 'Briefs and terms', 'worker', ['claude-code'],
    'Writes creator briefs from the angle bank, with disclosure rules and whitelisting terms.',
    'Brief the creators', 'Angle bank, disclosure, whitelisting.',
    ['Take the lane, angle and format for the creator',
     'Write the brief with the allowlist claims and the disclosure rules',
     'Include the whitelisting terms so winners can go paid',
     'Send through Compliance Auditor',
     'Deliver to the creator and log the due date']),
  c('twenty-one-nights-producer', '21 Nights Producer', 'The documented series', 'specialist', ['claude-code', 'zernio'],
    'Runs the day 1, day 7, day 21 series across creators in parallel, wearable data on screen.',
    'Run the 21 Nights series', 'Day 1, 7, 21, in parallel.',
    ['Enrol each new creator into the series with a start date',
     'Send the day 1, day 7 and day 21 prompts on schedule',
     'Collect the wearable screenshots and the video for each episode',
     'Pass each episode through Compliance Auditor',
     'Schedule episodes with Publisher so a series episode lands every week',
     'Report completion rate to Performance Reader'],
    true, ['6 creators in the series; 3 at day 7, 2 at day 21, 1 enrolled today', 'Day 21 episode from the shift-worker lane: deep sleep up on screen, cleared by Compliance', 'Series completion rate 83%', 'Two day-21 episodes flagged as winners for paid']),
  c('performance-reader', 'Performance Reader', 'Kill and promote', 'specialist', ['zernio', 'claude-code'],
    'Kills losers, flags winners to Growth\'s Campaign Launcher, writes learnings back to the planner.',
    'Read performance and decide', 'Kill, promote, learn.',
    ['Pull 48-hour performance for every post against its hypothesis',
     'Kill posts under the floor and record why',
     'Flag posts above the promote line to Growth\'s Campaign Launcher for paid',
     'Write the learning per hypothesis back to Content Planner',
     'Update the hit rate per lane and format',
     'Hand the winner list to Translator'],
    true, ['Week 36: 21 posts read, 9 killed, 2 promoted to paid, hit rate 9.5%', 'Winner flagged to Campaign Launcher: wearable before-and-after, shift-worker lane', 'Parent POV format hit rate up to 14% over four weeks', 'Learning filed: physician explainer underperforms without a face']),
];
