import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'growth-planner';
const g = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.growth, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const GROWTH: RosterEntry[] = [
  g('growth-planner', 'Growth Planner', 'Paid media plan and approvals', 'lead', ['claude-code', 'meta-ads', 'tiktok-ads', 'google-ads'],
    'Sets the week: audience lanes, angles, budget per platform. Holds the two approvals Yannick gives: the week, and spend on winners.',
    'Plan the week of paid media', 'Lanes, angles, budget, two approvals.',
    ['Read last week from Ads Reporter: spend, MER, CPA, winners, kills',
     'Pick this week\'s lanes (parents, shift workers, wearable optimisers, travellers) and angles (28-minute sunset, no app, patent, guarantee)',
     'Set budget per platform against the contribution margin floor from Finance',
     'Brief Creative Strategist with one hypothesis per asset slot',
     'Send the week to Yannick for approval; nothing launches before the yes',
     'Queue winner amplification requests for the second approval, spend only'],
    true, ['Week 37 planned: 4 lanes, 6 angles, 22 asset slots, budget split Meta 55 / TikTok 35 / Google 10', 'Approval request sent to Yannick: week plan plus 2 winner amplifications', 'Budget floor from Contribution Margin honoured: CPA ceiling $46 on Sleep', 'Reallocated 12% from Google Shopping to TikTok after Budget Auditor flagged marginal return']),
  g('competitor-researcher', 'Competitor Researcher', 'Category and rival ads watch', 'worker', ['claude-code', 'meta-ads', 'apify'],
    'Watches rival ads in the Meta ads library, rising TikTok formats, and objections in comments and reviews.',
    'Scan the category weekly', 'Rival ads, rising formats, objections.',
    ['Pull active ads for Hatch, Loftie, Therabody and Somnee from the Meta ads library',
     'List new hooks, offers and formats seen this week',
     'Read comments and reviews for repeated objections (price, does it work, safe for kids)',
     'Write the signal note: three things to copy, three to avoid',
     'Hand the note to Creative Strategist and Hook Miner']),
  g('creative-strategist', 'Creative Strategist', 'Briefs with a hypothesis', 'worker', ['claude-code'],
    'Turns lanes and angles into briefs, one hypothesis per asset.',
    'Write the asset briefs', 'Lane times angle times format, one hypothesis each.',
    ['Take the week\'s lanes and angles from Growth Planner',
     'Pair each with a format that fits (wearable before and after, parent POV, physician explainer, debunk, unboxing)',
     'Write the hypothesis each asset tests, one line',
     'Attach the claims each brief may use from the allowlist',
     'Send briefs to Ad Copywriter and Visual Designer']),
  g('ad-copywriter', 'Ad Copywriter', 'Hooks and scripts at volume', 'specialist', ['claude-code'],
    'Writes hooks and scripts at volume against structures already proven in the category.',
    'Write hooks and scripts', 'Volume against proven structures.',
    ['Take the briefs and the hook templates from Hook Miner',
     'Write eight hooks per brief, each on a different structure',
     'Write the primary text and the script per format',
     'Mark every claim with its allowlist id so Compliance Auditor can check it',
     'Deliver the batch as a variant sheet named by lane and angle',
     'Log which structures shipped so next week starts from what worked'],
    true, ['Wrote 48 hooks for 6 briefs; 11 flagged to Compliance Auditor, 3 rewritten', 'Sunset-mimic angle: 8 hooks, 2 promoted by Performance Reader', 'Parent lane scripts delivered, 4 formats, French variants requested', 'Rewrote 3 hooks that leaned on "cures insomnia"; replaced with sleep onset language from the allowlist']),
  g('visual-designer', 'Visual Designer', 'Stills, product shots, UGC variants', 'worker', ['claude-code', 'arcads', 'higgsfield'],
    'Produces stills, product shots and UGC variants from the briefs, using the approved product photography in the brand pack.',
    'Produce the visual assets', 'Stills, product shots, UGC from the briefs.',
    ['Read the brief and pull the approved product photography from Brand Pack Keeper',
     'Generate stills and product-in-bedroom scenes to the brief',
     'Generate UGC variants through Arcads for the volume slots',
     'Cull to the strongest takes before any upscale spend',
     'Hand finals to Format Checker with the brief attached']),
  g('format-checker', 'Format Checker', 'Platform spec verification', 'worker', ['claude-code'],
    'Verifies every asset against current Meta, TikTok and Google specs, including the AI-generated content disclosure.',
    'Check formats before launch', 'Specs, crops, disclosure.',
    ['Take each final from Visual Designer',
     'Check dimensions, duration, safe zones and text density per platform',
     'Confirm the AI-generated content disclosure is set where the asset is synthetic',
     'Reject with a one-line reason so the fix is fast',
     'Pass approved assets to Compliance Auditor']),
  g('compliance-auditor', 'Compliance Auditor', 'Claims gate', 'specialist', ['claude-code', 'gbrain'],
    'Blocks any asset with a claim outside the substantiated allowlist. Sleep and health claims never ship unchecked. Shared with Content.',
    'Gate every claim', 'Allowlist in, nothing else out.',
    ['Load the claims allowlist from the brain (patent, 630 nm, 28-minute cycle, survey figures with method note, guarantee terms)',
     'Read every hook, script and caption in the batch',
     'Block anything that promises a medical outcome, names a condition, or cites an unsourced figure',
     'Return each block with the allowlist line that could replace it',
     'Log the block rate per writer so the pattern is visible',
     'Release the batch to Campaign Launcher or Publisher only when zero blocks remain'],
    true, ['Batch 37-B: 62 assets checked, 7 blocked, 7 rewritten, 0 shipped with open blocks', 'Blocked "clinically proven to cure insomnia"; replaced with "backed by the 2018 sleep onset study"', 'Allowlist refreshed from Evidence Curator: Strasbourg 2024 added', 'TikTok health policy check passed on 14 creator videos']),
  g('translator', 'Translator', 'Winners only into French and German', 'worker', ['claude-code'],
    'Turns winners only into French and German, matching the store\'s locales. Shared with Content.',
    'Localise the winners', 'French and German, winners only.',
    ['Take only assets flagged winner by Performance Reader or Budget Auditor',
     'Translate hooks and scripts into French and German with the brand glossary',
     'Keep every claim on the allowlist wording in each language',
     'Send back through Compliance Auditor',
     'Deliver to Campaign Launcher with locale tags']),
  g('campaign-launcher', 'Campaign Launcher', 'Structured launch per platform', 'worker', ['meta-ads', 'tiktok-ads', 'google-ads'],
    'Pushes approved assets into Meta, TikTok and Google, structured per platform.',
    'Launch approved campaigns', 'Approved assets in, structured campaigns out.',
    ['Take the approved batch and the budget from Growth Planner',
     'Build the campaign structure per platform: one campaign per lane, one ad set per angle',
     'Upload assets with naming that Tracking Auditor can read back',
     'Set the conversion event and attribution window agreed with Tracking Auditor',
     'Launch and confirm delivery within the hour']),
  g('meta-ads-auditor', 'Meta Ads Auditor', 'Meta account health', 'specialist', ['meta-ads'],
    'Audits the Meta account: Pixel and Conversions API, audiences, placements, creative fatigue, account structure.',
    'Audit the Meta account', 'Pixel, CAPI, audiences, fatigue.',
    ['Check Pixel and Conversions API events match: purchase, add to cart, view content',
     'Review audience overlap and exclusions across ad sets',
     'Flag creatives past the fatigue threshold (frequency and falling CTR)',
     'Check placements and Advantage+ settings against the plan',
     'Write findings with evidence and hand fixes to Campaign Launcher',
     'Report account health score to Ads Reporter'],
    true, ['Account health 82/100: CAPI dedup fixed, 3 fatigued creatives paused', 'Purchase event mismatch found between Pixel and CAPI; dedup key set', 'Audience overlap 34% between parents and travellers ad sets; exclusions added', 'Advantage+ shopping campaign structure verified against the plan']),
  g('tiktok-ads-auditor', 'TikTok Ads Auditor', 'TikTok account health', 'worker', ['tiktok-ads'],
    'Audits TikTok Ads: Events API, Smart+, Shop campaigns, creative-native fit.',
    'Audit the TikTok account', 'Events API, Smart+, Shop.',
    ['Check Events API coverage for the purchase and add to cart events',
     'Review Smart+ campaign settings and the Shop campaign link',
     'Flag creatives that read as ads rather than native posts',
     'Check pacing against the plan',
     'Write findings and hand fixes to Campaign Launcher']),
  g('google-ads-auditor', 'Google Ads Auditor', 'Google account health', 'worker', ['google-ads'],
    'Audits Google Ads: brand search, Shopping, Performance Max, negatives.',
    'Audit the Google account', 'Brand search, Shopping, PMax.',
    ['Check conversion tracking and the Shopping feed status',
     'Review brand search terms and add negatives for competitor and irrelevant queries',
     'Check Performance Max asset groups against the brand pack',
     'Check pacing against the plan',
     'Write findings and hand fixes to Campaign Launcher']),
  g('budget-auditor', 'Budget Auditor', 'Pacing and marginal return', 'specialist', ['meta-ads', 'tiktok-ads', 'google-ads'],
    'Daily pacing, marginal return per platform, when to scale or cut.',
    'Audit pacing daily', 'Pacing, marginal return, scale or cut.',
    ['Read yesterday\'s spend and results per platform',
     'Compare pacing to the week\'s budget',
     'Compute marginal return per platform against the CPA ceiling from Contribution Margin',
     'Recommend scale, hold or cut per campaign with the number that decided it',
     'Send scale recommendations to Growth Planner for the spend approval',
     'Log the decision so Ads Reporter can show it Monday'],
    true, ['Day 4 pacing 98%; TikTok marginal CPA $38 under the $46 ceiling, scale recommended', 'Cut Google Shopping by 20%: marginal CPA $71', 'Meta parents lane: scale 25% approved by Yannick', 'Held all budgets: Friday spend spike without matching purchases, tracking check requested']),
  g('experiment-designer', 'Experiment Designer', 'Kill and promote rules', 'worker', ['claude-code'],
    'Designs the tests: kill and promote rules, sample sizes, what each test decides.',
    'Design the experiments', 'Rules, sample sizes, decisions.',
    ['Take the hypotheses from Creative Strategist',
     'Set the metric, the sample size and the duration each needs',
     'Write the kill rule and the promote rule before launch',
     'Check the test does not overlap another on the same audience',
     'Read results with Performance Reader and record the decision']),
  g('tracking-auditor', 'Tracking Auditor', 'Events and attribution', 'worker', ['meta-ads', 'tiktok-ads', 'google-ads', 'shopify'],
    'Audits conversion events, deduplication, and attribution windows across platforms.',
    'Audit tracking weekly', 'Events, dedup, windows.',
    ['Compare Shopify orders to platform-reported purchases for the week',
     'Check event deduplication between browser and server',
     'Check attribution windows match across Meta, TikTok and Google',
     'Flag any gap above ten percent with the likely cause',
     'Hand fixes to the platform auditors and note the gap for Ads Reporter']),
  g('landing-page-auditor', 'Landing Page Auditor', 'Message match and friction', 'worker', ['claude-code', 'shopify'],
    'Checks message match from ad to product page and mobile friction after the click.',
    'Audit the landing pages', 'Message match, mobile, friction.',
    ['Open the product page each live campaign lands on, on mobile',
     'Check the hook\'s promise appears above the fold',
     'Check proof blocks, guarantee and price are visible without scrolling far',
     'Time the page and flag anything over three seconds',
     'Send findings to Product Page Optimizer in Store']),
  g('ads-reporter', 'Ads Reporter', 'The Monday brief', 'specialist', ['claude-code', 'meta-ads', 'tiktok-ads', 'google-ads', 'shopify'],
    'Writes the Monday brief: spend, MER, CPA, contribution margin, winners and kills.',
    'Write the Monday brief', 'Spend, MER, CPA, margin, winners, kills.',
    ['Pull spend and results per platform for the week',
     'Compute blended MER and CPA per SKU',
     'Take contribution margin per SKU from Finance',
     'List winners promoted and losers killed, with the number behind each',
     'Write the brief in five lines for Yannick and file the full table',
     'Send the brief Monday 08:00 Hong Kong time'],
    true, ['Week 36 brief: spend $18.4k, MER 3.1, CPA $44 Sleep / $52 Kidzzz, 3 winners, 9 kills', 'Week 35 brief: spend $16.9k, MER 2.8, first French variants live', 'Brief sent Monday 08:00 HKT; Yannick approved 2 amplifications by 09:10', 'Week 34 brief: TikTok overtook Meta on marginal return for the first time']),
];
