import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'conductor';
const o = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.operations, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const OPERATIONS: RosterEntry[] = [
  o('conductor', 'Conductor', 'Routes directives, runs the loop', 'lead', ['broadcast', 'claude-code', 'gbrain'],
    'Routes directives across the pillars and runs the weekly loop: Content finds, Growth funds, Retention keeps.',
    'Conduct the weekly loop', 'Content finds, Growth funds, Retention keeps.',
    ['Receive the directive from the operator console',
     'Resolve the target: the whole fleet or one pillar',
     'Fan the message out and stamp each send',
     'Collect replies and file the run',
     'Monday: trigger Ads Reporter, Retention Reporter, Store Reporter, Care Reporter in that order',
     'Report non-responders after sixty seconds']),
  o('knowledge-agent', 'Knowledge Agent', 'Answers from the company brain', 'specialist', ['gbrain', 'brain-store'],
    'Answers questions from the company brain: the evidence base, the claims allowlist, the brand pack, past decisions.',
    'Answer from the brain', 'Evidence, allowlist, brand pack, decisions.',
    ['Take the question from the operator or an agent',
     'Search the brain: evidence base, allowlist, brand pack, decisions',
     'Answer with the page and the date of the source',
     'Say when nothing in the brain answers it',
     'Log the question so gaps become pages',
     'Report brain health with Brain Auditor'],
    true, ['Answered "what can we say about the survey" with the allowlist line and the method note', 'Answered "which study covers sleep onset" with the 2018 paper page', 'No page answers "return policy for Germany"; gap logged for Page Writer', 'Brain health 90/100']),
  o('brand-pack-keeper', 'Brand Pack Keeper', 'Versions the brand pack', 'specialist', ['gbrain', 'claude-code'],
    'Versions the brand context, logos, approved product photography and templates the producers draw from.',
    'Keep the brand pack', 'Context, logos, photography, templates, versioned.',
    ['Hold the current brand pack version and its manifest',
     'Approve new product photography only with its source and retouch note',
     'Publish template changes with a version bump',
     'Tell Visual Designer and Video Producer when the pack changes',
     'Keep release approval separate from asset approval',
     'Log every version in the brain'],
    true, ['Brand pack 2.4.0: two retouched studio product shots added, release approval pending', 'Product spotlight template published', 'Pack manifest verified against every asset hash', 'Visual Designer notified of the 2.4.0 photography']),
  o('brain-auditor', 'Brain Auditor', 'Markdown and vector health', 'worker', ['gbrain', 'brain-store', 'zeroentropy'],
    'Keeps the markdown store and the vector index healthy.',
    'Audit the brain', 'Markdown and vectors.',
    ['Check every page has frontmatter and a title',
     'Find broken links and orphan pages',
     'Compare the vector index to the page count',
     'Re-embed pages changed since the last audit',
     'Report health to Knowledge Agent']),
  o('connector-monitor', 'Connector Monitor', 'Honest connector status', 'worker', ['shopify', 'klaviyo', 'meta-ads', 'tiktok-ads', 'google-ads', 'amazon', 'zernio'],
    'Reports the honest status of every connector: connected or needs key.',
    'Monitor the connectors', 'Connected or needs key, never faked.',
    ['Check each connector\'s credential and a read call',
     'Mark connected, needs key, or failing with the error',
     'Post changes to Slack',
     'Never report connected without a successful read',
     'Report the board state to Scheduler']),
  o('scheduler', 'Scheduler', 'Cron runs and alerts', 'worker', ['claude-code'],
    'Runs the cron schedule for every agent, keeps the run log, raises failure alerts.',
    'Run the schedule', 'Cron, run log, alerts.',
    ['Load the schedule per agent',
     'Start runs on time and record start and finish',
     'Retry a failed run once',
     'Alert on a second failure with the summary',
     'Report run counts and failures weekly']),
  o('data-agent', 'Data Agent', 'Numbers for every reporter', 'worker', ['shopify', 'klaviyo', 'meta-ads', 'gbrain'],
    'Pulls numbers across connectors for every pillar\'s reporter.',
    'Serve the reporters', 'Numbers across connectors.',
    ['Take the metric request from a reporter',
     'Pull from the connector or the seeded table',
     'Return the number with its source and date',
     'Cache the answer for the rest of the day',
     'Log requests so missing metrics become connectors']),
];
