import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'lifecycle-planner';
const r = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.retention, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const RETENTION: RosterEntry[] = [
  r('lifecycle-planner', 'Lifecycle Planner', 'The flow map', 'lead', ['klaviyo', 'shopify', 'claude-code'],
    'Maps the flows: welcome, browse abandon, cart abandon, post-purchase, review request, win-back, gifting.',
    'Plan the lifecycle flows', 'Seven flows, owned and measured.',
    ['List the flows and the trigger for each',
     'Set the goal metric per flow (capture rate, recovery rate, repeat rate)',
     'Assign writers and the segments each flow uses',
     'Check every flow has a Compliance Auditor pass before it goes live',
     'Review flow revenue weekly with Flow Auditor',
     'Report the plan and its numbers to Retention Reporter'],
    true, ['Seven flows mapped; welcome and cart abandon live, post-purchase in review', 'Cart abandon recovery target 8%; current 6.4%', 'Gifting flow drafted for the Q4 season', 'Post-purchase flow rebuilt around the 21 nights']),
  r('segment-builder', 'Segment Builder', 'Lanes as segments', 'worker', ['klaviyo'],
    'Turns the audience lanes into Klaviyo segments: parents, shift workers, wearable optimisers, travellers, couples.',
    'Build the segments', 'Lanes into Klaviyo segments.',
    ['Define each lane by product bought, quiz answer or source campaign',
     'Build the segment and check its size',
     'Add the engaged and lapsed variants per segment',
     'Hand segment ids to the writers',
     'Refresh sizes weekly for Retention Reporter']),
  r('email-writer', 'Email Writer', 'Flow and campaign copy', 'worker', ['klaviyo', 'claude-code'],
    'Writes copy for every flow and campaign in the brand voice from the brand pack.',
    'Write the emails', 'Flows and campaigns, brand voice.',
    ['Take the flow or campaign brief and its segment',
     'Write subject, preview and body in the brand voice',
     'Use only allowlist claims and mark each',
     'Send through Compliance Auditor',
     'Deliver to Lifecycle Planner with the send window']),
  r('sms-writer', 'SMS Writer', 'Short check-ins', 'worker', ['klaviyo', 'claude-code'],
    'Writes SMS: cart, shipping, night 7 and night 21 check-ins.',
    'Write the SMS', 'Cart, shipping, night 7, night 21.',
    ['Take the trigger and the segment',
     'Write the message under 160 characters with one link',
     'Check consent and quiet hours per country',
     'Send through Compliance Auditor',
     'Deliver to Lifecycle Planner']),
  r('campaign-composer', 'Campaign Composer', 'Weekly sends', 'worker', ['klaviyo', 'claude-code'],
    'Composes the weekly sends: education, proof, seasonal, gifting.',
    'Compose the weekly campaign', 'Education, proof, seasonal, gifting.',
    ['Pick this week\'s theme from the content calendar',
     'Reuse the week\'s winning hook where it fits',
     'Write the send with Email Writer',
     'Pick segments and the send time per region',
     'Log open and click rates for Retention Reporter']),
  r('twenty-one-nights-coach', '21 Nights Coach', 'Post-purchase onboarding', 'specialist', ['klaviyo', 'shopify'],
    'Runs the post-purchase sequence at day 1, 7 and 21. Keeps the device in use through the three weeks it needs, so fewer 60-day refunds, and asks for the review on the right night.',
    'Coach the first 21 nights', 'Day 1, 7, 21. Fewer refunds, better reviews.',
    ['Trigger on order delivered',
     'Day 1: how to place it, the 28-minute cycle, what to expect in week one',
     'Day 7: check in, answer the top three first-week questions',
     'Day 21: ask how the nights went and request the review',
     'Route anyone reporting no change to Refund Handler before the guarantee window closes',
     'Report completion and refund rate against non-coached buyers'],
    true, ['1,240 buyers in the sequence; day-21 review request click rate 18%', 'Refund rate for coached buyers 3.1% against 5.8% uncoached', 'Day 7 reply "still waking at 3am" routed to Refund Handler with the coaching path first', 'Sequence localised to French for Quebec orders']),
  r('offer-designer', 'Offer Designer', 'Bundles and second device', 'specialist', ['shopify', 'claude-code'],
    'Designs bundles and second-device offers: Sleep x2, Sleep plus Kidzzz, gifting, guarantee framing.',
    'Design the offers', 'Bundles, second device, guarantee framing.',
    ['Read repeat and bundle data from Shopify',
     'Design one offer per lane: partner device, child device, gift',
     'Frame the guarantee as risk reversal in every offer',
     'Check margin per offer with Contribution Margin',
     'Hand the offer to Promo Planner in Store and Campaign Composer',
     'Read results after two weeks and keep or kill'],
    true, ['Sleep plus Kidzzz bundle: attach rate 11% in week one', 'Partner device offer at day 30: 6% take rate', 'Gift offer margin checked: 41% after shipping']),
  r('referral-runner', 'Referral Runner', 'Couples and parents refer', 'worker', ['klaviyo', 'shopify'],
    'Runs referrals: couples and parents refer; partner and second bedroom offers.',
    'Run the referral loop', 'Refer a partner, a parent, a friend.',
    ['Trigger at day 30 for buyers with a review or a repeat',
     'Offer the referral reward and the partner device link',
     'Track referred orders back to the referrer',
     'Pay out rewards weekly',
     'Report referral share of orders to Retention Reporter']),
  r('win-back-writer', 'Win-back Writer', 'Lapsed and abandoned', 'worker', ['klaviyo', 'claude-code'],
    'Writes win-back for lapsed browsers, carts past the flow, and gift-season returns.',
    'Write the win-back', 'Lapsed browsers, old carts, gift season.',
    ['Pull segments lapsed 30, 60 and 90 days',
     'Write one message per lapse window with a different reason to return',
     'Use the guarantee and the 21 nights as the argument, never discounts first',
     'Send through Compliance Auditor',
     'Report recovered orders to Retention Reporter']),
  r('flow-auditor', 'Flow Auditor', 'Deliverability and list health', 'worker', ['klaviyo'],
    'Audits deliverability, list health, and flow versus campaign revenue share.',
    'Audit the flows', 'Deliverability, list health, revenue share.',
    ['Check bounce, spam and unsubscribe rates per flow',
     'Check list growth against the capture flows',
     'Compute flow versus campaign revenue share',
     'Flag any flow with falling revenue for two weeks',
     'Report to Lifecycle Planner']),
  r('retention-reporter', 'Retention Reporter', 'Repeat, flow revenue, refunds', 'worker', ['klaviyo', 'shopify'],
    'Reports repeat rate, flow revenue, refund rate against the guarantee, and list growth.',
    'Report retention weekly', 'Repeat, flows, refunds, list.',
    ['Pull repeat rate and second-device rate from Shopify',
     'Pull flow and campaign revenue from Klaviyo',
     'Pull refund rate inside the 60-day window',
     'Write five lines for Yannick with the trend per line',
     'File the table and send Monday with the Ads Reporter brief']),
];
