import { DEPT } from './types';
import type { RosterEntry } from './types';

const LEAD = 'store-auditor';
const s = (
  id: string, name: string, role: string, tier: RosterEntry['tier'], tools: string[],
  description: string, sopTitle: string, sopSummary: string, steps: string[],
  hero = false, runSummaries: string[] = [`${name} completed a run.`],
): RosterEntry => ({
  id, departmentId: DEPT.store, name, role, tier, parentId: tier === 'lead' ? null : LEAD,
  description, model: 'claude-sonnet-5 via Claude Code skills', tools, sopTitle, sopSummary, steps, hero, runSummaries,
});

export const STORE: RosterEntry[] = [
  s('store-auditor', 'Store Auditor', 'Weekly storefront crawl', 'lead', ['shopify', 'claude-code'],
    'Crawls the storefront weekly: empty pages, dead nav items, broken comparison rows, dates that disagree.',
    'Audit the storefront', 'Empty pages, dead nav, broken rows.',
    ['Crawl every page in the sitemap on desktop and mobile',
     'Flag pages that render no body content',
     'Flag nav items pointing at out-of-stock or unbuyable products',
     'Flag any claim or date that disagrees with another page',
     'Open one ticket per finding with the fix owner',
     'Report open and closed findings to Store Reporter'],
    true, ['Crawl: 4 pages render empty (science, doctor-recommended, compare, better-sleep); tickets opened', 'Nightlight out of stock and still in the nav; Catalog Keeper ticket', 'Founding dates disagree across homepage, About and protocol page; Page Writer ticket', 'Care row in the comparison table has no product; Catalog Keeper ticket']),
  s('seo-auditor', 'SEO Auditor', 'Technical SEO and locales', 'worker', ['claude-code'],
    'Audits technical SEO, duplicate blog titles, and locale handling across EN, FR and DE.',
    'Audit SEO monthly', 'Technical, duplicates, locales.',
    ['Check indexing, canonicals and hreflang across the three locales',
     'Flag duplicate titles and near-duplicate posts',
     'Check Core Web Vitals on the product pages',
     'List the top ten queries the site should own and does not',
     'Hand fixes to Page Writer and Blog Writer']),
  s('evidence-curator', 'Evidence Curator', 'The evidence base', 'specialist', ['gbrain', 'claude-code'],
    'Keeps the evidence base: patents, study chain, clinician positions, awards, survey. Structured, sourced, dated, checkable.',
    'Curate the evidence', 'Patents, studies, clinicians, awards, survey.',
    ['List every claim the brand makes and the source behind it',
     'File each source in the brain with date, jurisdiction and a link',
     'Mark claims with no source as unsubstantiated and tell Compliance Auditor',
     'Keep the survey figures paired with a method note',
     'Publish the allowlist from the sourced claims',
     'Review quarterly for new studies'],
    true, ['Evidence base: 7 patent filings, 6 studies, 3 clinicians, 4 awards filed with sources', 'Survey figures (98 / 96 / 86 percent) marked "method not published"; allowlist wording adjusted', 'Strasbourg 2024 study added; Compliance Auditor notified', 'NFL and NBA usage marked as claimed, not verified']),
  s('page-writer', 'Page Writer', 'Fills the empty pages', 'worker', ['shopify', 'claude-code'],
    'Fills science, doctor-recommended, compare and better-sleep from the curated evidence.',
    'Write the proof pages', 'Four empty pages, filled from evidence.',
    ['Take the evidence base from Evidence Curator',
     'Write the science page as a sourced, dated list, not prose',
     'Write doctor-recommended with each clinician\'s position and link',
     'Write compare against Hatch, Loftie and melatonin, with the no-app angle',
     'Send through Compliance Auditor and publish']),
  s('ai-answer-optimizer', 'AI Answer Optimizer', 'Own the assistant answer', 'specialist', ['claude-code'],
    'Rewrites agents.md and llms.txt, adds schema, and tracks whether ChatGPT, Claude and Perplexity cite Helight for "what helps me fall asleep".',
    'Optimise for AI answers', 'agents.md, llms.txt, schema, citations.',
    ['Replace the Shopify boilerplate agents.md with Helight\'s product, protocol, evidence and audience',
     'Write llms.txt pointing at the proof pages and the catalog',
     'Add product, organisation and FAQ schema to the key pages',
     'Ask the same ten sleep questions to three assistants weekly and record who gets cited',
     'Report share of voice against Hatch, Loftie and Therabody',
     'Hand content gaps to Blog Writer'],
    true, ['agents.md rewritten: 1,900 words on the product, the protocol and the evidence', 'Citation check: Helight cited in 3 of 10 answers, up from 0', 'FAQ schema added to the science page', 'Gap found: no page answers "is red light safe for babies"; Blog Writer ticket']),
  s('product-page-optimizer', 'Product Page Optimizer', 'Conversion on the PDP', 'specialist', ['shopify', 'claude-code'],
    'Works the product pages: message match, proof blocks, mobile friction, guarantee placement.',
    'Optimise the product pages', 'Message match, proof, mobile, guarantee.',
    ['Take findings from Landing Page Auditor in Growth',
     'Move proof and guarantee above the fold on mobile',
     'Match the page headline to the live winning hook',
     'Cut page weight until it loads under three seconds',
     'Hand each change to Storefront Tester as a test',
     'Report conversion rate per page to Store Reporter'],
    true, ['Sleep PDP: guarantee moved above the fold, mobile conversion 2.1 to 2.6 percent in test', 'Headline matched to the sunset-mimic hook for the parents campaign', 'Page weight cut 38%, load 2.4 seconds on 4G']),
  s('storefront-tester', 'Storefront Tester', 'A/B on the store', 'worker', ['shopify'],
    'Runs A/B tests on offers, guarantee wording, and bundle placement.',
    'Run storefront tests', 'Offers, guarantee, bundles.',
    ['Take the change from Product Page Optimizer or Offer Designer',
     'Set the metric, sample size and duration',
     'Run the test on one page at a time',
     'Read the result and record the decision',
     'Report wins and losses to Store Reporter']),
  s('blog-writer', 'Blog Writer', 'Product-led posts', 'worker', ['shopify', 'claude-code'],
    'Writes product-led, comparison and objection posts instead of sleep-wellness prose.',
    'Write the blog', 'Product-led, comparison, objection.',
    ['Take the gap list from AI Answer Optimizer and SEO Auditor',
     'Write one post per gap, answering the question in the first paragraph',
     'Use the evidence base for every figure',
     'Send through Compliance Auditor',
     'Publish and add to llms.txt']),
  s('catalog-keeper', 'Catalog Keeper', 'SKUs, stock, locales', 'worker', ['shopify', 'amazon'],
    'Keeps SKUs, variants, stock and locales straight. Flags the out-of-stock nightlight and the unbuyable Care row.',
    'Keep the catalog', 'SKUs, stock, locales.',
    ['Check stock per SKU and variant daily',
     'Hide or label out-of-stock items in the nav',
     'Remove or fix comparison rows for products not for sale',
     'Check price and copy parity across EN, FR and DE',
     'Report stock days remaining to Promo Planner and Finance']),
  s('promo-planner', 'Promo Planner', 'Calendar and bundle rules', 'worker', ['shopify', 'claude-code'],
    'Plans the promo calendar, bundle rules and gifting seasons.',
    'Plan the promos', 'Calendar, bundles, gifting.',
    ['Build the calendar around gifting seasons and the content calendar',
     'Take offers from Offer Designer and set the bundle rules',
     'Check margin per promo with Contribution Margin',
     'Brief Campaign Composer and Growth Planner two weeks ahead',
     'Read results and keep or kill each promo']),
  s('amazon-listing-auditor', 'Amazon Listing Auditor', 'Seller Central health', 'worker', ['amazon'],
    'Audits the Amazon listing: health, reviews, Sponsored Products.',
    'Audit the Amazon listing', 'Listing, reviews, Sponsored Products.',
    ['Check listing content and images against the brand pack',
     'Read new reviews and flag one and two stars to Review Monitor',
     'Check Sponsored Products spend and ACOS',
     'Check Buy Box and stock',
     'Report to Store Reporter']),
  s('store-reporter', 'Store Reporter', 'Sessions, conversion, AOV', 'worker', ['shopify'],
    'Reports sessions, conversion rate and AOV by locale and device.',
    'Report the store weekly', 'Sessions, conversion, AOV.',
    ['Pull sessions, conversion rate and AOV from Shopify',
     'Split by locale and device',
     'Add open audit findings and test results',
     'Write five lines for Yannick',
     'File the table and send Monday']),
];
