import type { Workflow, AgentTask, Skill } from '@/lib/schemas';

// The machine, mapped: each Helight process as an owned chain of steps.
// Real-ready: owners, weekly hours, tools, the bottlenecks that leak money,
// and the automations (live or suggested) that carry the load back.
export const workflows: Workflow[] = [
  {
    id: 'wf-content-engine',
    name: 'Content engine',
    subtitle: 'Signal to publish to analysis, weekly.',
    revenueUsd: 38_000,
    order: 0,
    steps: [
      {
        id: 'wf-ce-1',
        title: 'Watch the creators',
        ownerKind: 'agent',
        owner: 'Creator Watcher',
        hoursPerWeek: 2,
        tools: ['apify'],
        edgeLabel: '25 outliers',
        leakUsd: null,
        automation: { title: 'Watchlist scrape', state: 'live', recoveredUsd: 900 },
      },
      {
        id: 'wf-ce-2',
        title: 'Mine hooks and write scripts',
        ownerKind: 'agent',
        owner: 'Hook Miner',
        hoursPerWeek: 4,
        tools: ['claude-code'],
        edgeLabel: '19 scripts',
        leakUsd: null,
        automation: { title: 'Vault templates', state: 'live', recoveredUsd: 1400 },
      },
      {
        id: 'wf-ce-3',
        title: 'Produce and edit',
        ownerKind: 'agent',
        owner: 'Video Producer',
        hoursPerWeek: 6,
        tools: ['arcads', 'remotion'],
        edgeLabel: '19 cuts',
        leakUsd: 1200,
        automation: { title: 'Human edit queue', state: 'suggested', recoveredUsd: 600 },
      },
      {
        id: 'wf-ce-4',
        title: 'Approve the week',
        ownerKind: 'human',
        owner: 'Yannick · Operator',
        hoursPerWeek: 1,
        tools: [],
        edgeLabel: 'yes',
        leakUsd: null,
        automation: null,
      },
      {
        id: 'wf-ce-5',
        title: 'Publish and read',
        ownerKind: 'agent',
        owner: 'Publisher',
        hoursPerWeek: 3,
        tools: ['zernio'],
        edgeLabel: '2 winners',
        leakUsd: null,
        automation: { title: 'Kill and promote', state: 'live', recoveredUsd: 2100 },
      },
    ],
  },
  {
    id: 'wf-paid-amplification',
    name: 'Paid amplification',
    subtitle: 'Winner to launch to Monday brief.',
    revenueUsd: 52_000,
    order: 1,
    steps: [
      {
        id: 'wf-pa-1',
        title: 'Take the winner',
        ownerKind: 'agent',
        owner: 'Performance Reader',
        hoursPerWeek: 1,
        tools: ['zernio'],
        edgeLabel: 'winner',
        leakUsd: null,
        automation: { title: 'Winner handoff to paid', state: 'live', recoveredUsd: 700 },
      },
      {
        id: 'wf-pa-2',
        title: 'Gate the claims',
        ownerKind: 'agent',
        owner: 'Compliance Auditor',
        hoursPerWeek: 1,
        tools: ['claude-code', 'gbrain'],
        edgeLabel: 'cleared',
        leakUsd: null,
        automation: { title: 'Allowlist gate', state: 'live', recoveredUsd: 3000 },
      },
      {
        id: 'wf-pa-3',
        title: 'Approve spend',
        ownerKind: 'human',
        owner: 'Yannick · Operator',
        hoursPerWeek: 0.5,
        tools: [],
        edgeLabel: 'amount',
        leakUsd: null,
        automation: null,
      },
      {
        id: 'wf-pa-4',
        title: 'Launch per platform',
        ownerKind: 'agent',
        owner: 'Campaign Launcher',
        hoursPerWeek: 2,
        tools: ['meta-ads', 'tiktok-ads', 'google-ads'],
        edgeLabel: 'live',
        leakUsd: null,
        automation: { title: 'Per-platform launch', state: 'live', recoveredUsd: 900 },
      },
      {
        id: 'wf-pa-5',
        title: 'Pace and report',
        ownerKind: 'agent',
        owner: 'Budget Auditor',
        hoursPerWeek: 3,
        tools: ['meta-ads', 'tiktok-ads', 'google-ads'],
        edgeLabel: 'brief',
        leakUsd: 800,
        automation: { title: 'Daily pacing alerts', state: 'suggested', recoveredUsd: 1600 },
      },
    ],
  },
  {
    id: 'wf-first-to-second',
    name: 'First order to second device',
    subtitle: 'Klaviyo flows from welcome to referral.',
    revenueUsd: 21_000,
    order: 2,
    steps: [
      {
        id: 'wf-fts-1',
        title: 'Capture the email',
        ownerKind: 'agent',
        owner: 'Segment Builder',
        hoursPerWeek: 1,
        tools: ['klaviyo'],
        edgeLabel: 'captured',
        leakUsd: null,
        automation: { title: 'Email capture flow', state: 'live', recoveredUsd: 500 },
      },
      {
        id: 'wf-fts-2',
        title: 'Coach 21 nights',
        ownerKind: 'agent',
        owner: '21 Nights Coach',
        hoursPerWeek: 2,
        tools: ['klaviyo', 'shopify'],
        edgeLabel: 'night 21',
        leakUsd: 1500,
        automation: { title: 'Day 1, 7, 21 sequence', state: 'live', recoveredUsd: 2400 },
      },
      {
        id: 'wf-fts-3',
        title: 'Ask for the review',
        ownerKind: 'agent',
        owner: '21 Nights Coach',
        hoursPerWeek: 0.5,
        tools: ['klaviyo'],
        edgeLabel: 'review',
        leakUsd: null,
        automation: { title: 'Night 21 review request', state: 'live', recoveredUsd: 400 },
      },
      {
        id: 'wf-fts-4',
        title: 'Offer the second device',
        ownerKind: 'agent',
        owner: 'Offer Designer',
        hoursPerWeek: 1,
        tools: ['shopify', 'klaviyo'],
        edgeLabel: 'bundle',
        leakUsd: null,
        automation: { title: 'Partner device at day 30', state: 'suggested', recoveredUsd: 1800 },
      },
      {
        id: 'wf-fts-5',
        title: 'Run the referral',
        ownerKind: 'agent',
        owner: 'Referral Runner',
        hoursPerWeek: 1,
        tools: ['klaviyo'],
        edgeLabel: 'referred order',
        leakUsd: null,
        automation: { title: 'Referral reward', state: 'suggested', recoveredUsd: 900 },
      },
    ],
  },
  {
    id: 'wf-storefront-loop',
    name: 'Storefront loop',
    subtitle: 'Crawl to evidence to proof pages to test, weekly. Runs without Yannick.',
    revenueUsd: 0,
    order: 3,
    steps: [
      {
        id: 'wf-sl-1',
        title: 'Crawl the storefront',
        ownerKind: 'agent',
        owner: 'Store Auditor',
        hoursPerWeek: 2,
        tools: ['shopify', 'claude-code'],
        edgeLabel: '4 findings',
        leakUsd: null,
        automation: { title: 'Weekly crawl', state: 'live', recoveredUsd: 700 },
      },
      {
        id: 'wf-sl-2',
        title: 'Curate the evidence',
        ownerKind: 'agent',
        owner: 'Evidence Curator',
        hoursPerWeek: 3,
        tools: ['gbrain', 'claude-code'],
        edgeLabel: 'allowlist',
        leakUsd: null,
        automation: { title: 'Sourced allowlist', state: 'live', recoveredUsd: 800 },
      },
      {
        id: 'wf-sl-3',
        title: 'Write the proof pages',
        ownerKind: 'agent',
        owner: 'Page Writer',
        hoursPerWeek: 4,
        tools: ['shopify', 'claude-code'],
        edgeLabel: '4 pages',
        leakUsd: 1500,
        automation: { title: 'Evidence to page', state: 'suggested', recoveredUsd: 900 },
      },
      {
        id: 'wf-sl-4',
        title: 'Optimise and test the PDP',
        ownerKind: 'agent',
        owner: 'Product Page Optimizer',
        hoursPerWeek: 3,
        tools: ['shopify'],
        edgeLabel: '1 test',
        leakUsd: null,
        automation: { title: 'Guarantee above the fold', state: 'live', recoveredUsd: 1100 },
      },
      {
        id: 'wf-sl-5',
        title: 'Report the store',
        ownerKind: 'agent',
        owner: 'Store Reporter',
        hoursPerWeek: 1,
        tools: ['shopify'],
        edgeLabel: null,
        leakUsd: null,
        automation: { title: 'Monday five lines', state: 'live', recoveredUsd: 300 },
      },
    ],
  },
  {
    id: 'wf-customer-care',
    name: 'Customer care',
    subtitle: 'Inbound to draft to send to guarantee to synthesis, daily. Agents draft, a human sends.',
    revenueUsd: 0,
    order: 4,
    steps: [
      {
        id: 'wf-cc-1',
        title: 'Triage inbound',
        ownerKind: 'agent',
        owner: 'Support Triage',
        hoursPerWeek: 3,
        tools: ['gmail', 'amazon'],
        edgeLabel: '44 action',
        leakUsd: null,
        automation: { title: 'Four-way triage', state: 'live', recoveredUsd: 1200 },
      },
      {
        id: 'wf-cc-2',
        title: 'Draft the replies',
        ownerKind: 'agent',
        owner: 'Reply Drafter',
        hoursPerWeek: 4,
        tools: ['gmail', 'gbrain'],
        edgeLabel: 'drafts',
        leakUsd: null,
        automation: { title: 'FAQ-backed drafts', state: 'live', recoveredUsd: 1600 },
      },
      {
        id: 'wf-cc-3',
        title: 'Send the replies',
        ownerKind: 'human',
        owner: 'Helight support',
        hoursPerWeek: 5,
        tools: ['gmail'],
        edgeLabel: 'sent',
        leakUsd: 2200,
        automation: { title: 'Allowlisted auto-send', state: 'suggested', recoveredUsd: 1400 },
      },
      {
        id: 'wf-cc-4',
        title: 'Handle the guarantee',
        ownerKind: 'agent',
        owner: 'Refund Handler',
        hoursPerWeek: 2,
        tools: ['shopify', 'klaviyo'],
        edgeLabel: '5 kept',
        leakUsd: null,
        automation: { title: '21 Nights path first', state: 'live', recoveredUsd: 2400 },
      },
      {
        id: 'wf-cc-5',
        title: 'Synthesise the voice',
        ownerKind: 'agent',
        owner: 'Voice of Customer',
        hoursPerWeek: 2,
        tools: ['claude-code', 'gbrain'],
        edgeLabel: null,
        leakUsd: null,
        automation: { title: 'Weekly synthesis', state: 'live', recoveredUsd: 500 },
      },
    ],
  },
  {
    id: 'wf-margin-loop',
    name: 'Margin loop',
    subtitle: 'Payouts to spend to margin to the CPA ceiling, weekly. The month closes on the third working day.',
    revenueUsd: 0,
    order: 5,
    steps: [
      {
        id: 'wf-ml-1',
        title: 'Reconcile payouts',
        ownerKind: 'agent',
        owner: 'Payments Pulse',
        hoursPerWeek: 2,
        tools: ['shopify', 'amazon'],
        edgeLabel: 'daily line',
        leakUsd: null,
        automation: { title: 'Payout reconciliation', state: 'live', recoveredUsd: 600 },
      },
      {
        id: 'wf-ml-2',
        title: 'Keep the spend ledger',
        ownerKind: 'agent',
        owner: 'Ad Spend Ledger',
        hoursPerWeek: 1,
        tools: ['meta-ads', 'tiktok-ads', 'google-ads'],
        edgeLabel: 'spend',
        leakUsd: null,
        automation: { title: 'Ledger against plan', state: 'live', recoveredUsd: 500 },
      },
      {
        id: 'wf-ml-3',
        title: 'Compute contribution margin',
        ownerKind: 'agent',
        owner: 'Contribution Margin',
        hoursPerWeek: 2,
        tools: ['shopify', 'claude-code'],
        edgeLabel: 'CPA ceiling',
        leakUsd: null,
        automation: { title: 'Margin per SKU', state: 'live', recoveredUsd: 1800 },
      },
      {
        id: 'wf-ml-4',
        title: 'Close the month',
        ownerKind: 'agent',
        owner: 'Month Close',
        hoursPerWeek: 3,
        tools: ['shopify', 'amazon', 'claude-code'],
        edgeLabel: '3 lines',
        leakUsd: 900,
        automation: { title: 'Close from the ledgers', state: 'suggested', recoveredUsd: 700 },
      },
      {
        id: 'wf-ml-5',
        title: 'Read the close',
        ownerKind: 'human',
        owner: 'Yannick · Operator',
        hoursPerWeek: 0.5,
        tools: [],
        edgeLabel: null,
        leakUsd: null,
        automation: null,
      },
    ],
  },
  {
    id: 'wf-weekly-loop',
    name: 'Weekly loop',
    subtitle: 'Directive to fan-out to schedule to numbers to answers. Content finds, Growth funds, Retention keeps.',
    revenueUsd: 0,
    order: 6,
    steps: [
      {
        id: 'wf-wl-1',
        title: 'Take the directive',
        ownerKind: 'human',
        owner: 'Yannick · Operator',
        hoursPerWeek: 0.5,
        tools: ['slack'],
        edgeLabel: 'directive',
        leakUsd: null,
        automation: null,
      },
      {
        id: 'wf-wl-2',
        title: 'Route and fan out',
        ownerKind: 'agent',
        owner: 'Conductor',
        hoursPerWeek: 1,
        tools: ['claude-code', 'gbrain'],
        edgeLabel: '7 pillars',
        leakUsd: null,
        automation: { title: 'Broadcast with stamps', state: 'live', recoveredUsd: 400 },
      },
      {
        id: 'wf-wl-3',
        title: 'Run the schedule',
        ownerKind: 'agent',
        owner: 'Scheduler',
        hoursPerWeek: 1,
        tools: ['claude-code'],
        edgeLabel: 'runs',
        leakUsd: null,
        automation: { title: 'Cron with one retry', state: 'live', recoveredUsd: 900 },
      },
      {
        id: 'wf-wl-4',
        title: 'Serve the numbers',
        ownerKind: 'agent',
        owner: 'Data Agent',
        hoursPerWeek: 2,
        tools: ['shopify', 'klaviyo', 'meta-ads'],
        edgeLabel: '4 briefs',
        leakUsd: 700,
        automation: { title: 'Live connectors', state: 'suggested', recoveredUsd: 1200 },
      },
      {
        id: 'wf-wl-5',
        title: 'Answer from the brain',
        ownerKind: 'agent',
        owner: 'Knowledge Agent',
        hoursPerWeek: 1,
        tools: ['gbrain'],
        edgeLabel: null,
        leakUsd: null,
        automation: { title: 'Brain answers with dates', state: 'live', recoveredUsd: 300 },
      },
    ],
  },
];

// Agent task board: seeded across open/doing/done so the Kanban is alive on
// first load. Demo cards; user-added tasks coexist (we insert by id, never
// wipe). Defined locally rather than imported from lib/seed.ts: that file
// imports this one, so importing back would be circular.
const SEED_TS = '2026-09-12T08:00:00Z';
export const agentTasks: AgentTask[] = [
  { id: 'task-seed-1', agentId: 'ad-copywriter', title: 'Write 8 hooks for the shift-worker lane', status: 'open', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-2', agentId: 'compliance-auditor', title: 'Clear batch 37-C before Thursday launch', status: 'open', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-3', agentId: 'creator-watcher', title: 'Add 4 creators in the menopause lane', status: 'open', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-4', agentId: 'page-writer', title: 'Draft the science page from the evidence base', status: 'open', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-5', agentId: 'publisher', title: "Schedule this week's 21 posts", status: 'doing', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-6', agentId: 'twenty-one-nights-coach', title: 'Localise the day-7 email to French', status: 'doing', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-7', agentId: 'meta-ads-auditor', title: 'Fix the purchase event dedup key', status: 'doing', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-8', agentId: 'ads-reporter', title: 'Send the week 36 brief', status: 'done', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-9', agentId: 'voice-of-customer', title: 'File the week 36 synthesis', status: 'done', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-10', agentId: 'catalog-keeper', title: 'Hide the out-of-stock nightlight from the nav', status: 'done', createdAt: SEED_TS, updatedAt: SEED_TS },
  { id: 'task-seed-11', agentId: 'brand-pack-keeper', title: 'Publish brand pack 2.4.0', status: 'done', createdAt: SEED_TS, updatedAt: SEED_TS },
];

// The capability library the agent workforce draws on.
export const skills: Omit<Skill, 'markdown'>[] = [
  { id: 'skill-claims-gate', name: 'Claims gate', category: 'Growth', description: 'Blocks any claim outside the substantiated allowlist before it ships.', ownerAgentId: 'compliance-auditor', status: 'live', tools: ['claude-code', 'gbrain'], order: 0, buildsOn: ['ads-creative', 'copywriting'] },
  { id: 'skill-hooks', name: 'Hook writing', category: 'Growth', description: 'Hooks at volume against structures proven in the category.', ownerAgentId: 'ad-copywriter', status: 'live', tools: ['claude-code'], order: 1, buildsOn: ['ad-creative', 'copywriting'] },
  { id: 'skill-meta-audit', name: 'Meta account audit', category: 'Growth', description: 'Pixel, CAPI, audiences, fatigue, structure.', ownerAgentId: 'meta-ads-auditor', status: 'live', tools: ['meta-ads'], order: 2, buildsOn: ['ads-meta', 'attribution'] },
  { id: 'skill-pacing', name: 'Budget pacing', category: 'Growth', description: 'Daily pacing and marginal return against the CPA ceiling.', ownerAgentId: 'budget-auditor', status: 'live', tools: ['meta-ads', 'tiktok-ads', 'google-ads'], order: 3, buildsOn: ['ads-budget', 'ads-monitor', 'ads-tiktok', 'ads-google'] },
  { id: 'skill-teardown', name: 'Video teardown', category: 'Content', description: 'Seven attributes per winning video.', ownerAgentId: 'video-analyst', status: 'learning', tools: ['claude-code'], order: 4, buildsOn: ['video', 'ad-creative'] },
  { id: 'skill-vault', name: 'Hook vault', category: 'Content', description: 'Winning hooks turned into slotted templates.', ownerAgentId: 'hook-miner', status: 'live', tools: ['gbrain'], order: 5, buildsOn: ['ad-creative', 'social'] },
  { id: 'skill-publish', name: 'Cadence publishing', category: 'Content', description: 'Daily posts across two platforms, never dark.', ownerAgentId: 'publisher', status: 'live', tools: ['zernio'], order: 6, buildsOn: ['social', 'influencer-marketing'] },
  { id: 'skill-21-nights', name: '21 Nights coaching', category: 'Retention', description: 'Day 1, 7, 21 post-purchase sequence.', ownerAgentId: 'twenty-one-nights-coach', status: 'learning', tools: ['klaviyo'], order: 7, buildsOn: ['emails', 'sms', 'churn-prevention'] },
  { id: 'skill-evidence', name: 'Evidence curation', category: 'Store', description: 'Sourced, dated, checkable claims.', ownerAgentId: 'evidence-curator', status: 'live', tools: ['gbrain'], order: 8, buildsOn: ['customer-research', 'cro', 'ads-landing'] },
  { id: 'skill-ai-answers', name: 'AI answer optimisation', category: 'Store', description: 'agents.md, llms.txt, schema, citation tracking.', ownerAgentId: 'ai-answer-optimizer', status: 'learning', tools: ['claude-code'], order: 9, buildsOn: ['ai-seo'] },
  { id: 'skill-triage', name: 'Inbound triage', category: 'Care', description: 'Skip, info, action, urgent.', ownerAgentId: 'support-triage', status: 'live', tools: ['support-inbox'], order: 10, buildsOn: ['customer-research'] },
  { id: 'skill-margin', name: 'Contribution margin', category: 'Ops', description: 'Margin per SKU after ads, shipping, refunds.', ownerAgentId: 'contribution-margin', status: 'live', tools: ['shopify'], order: 11, buildsOn: ['attribution', 'ads-budget'] },
];
